# This is a basic workflow to help you get started with Actions

name: Publish docker image

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ 9.0.x ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install s2i
        run: |
          set -x
          REMOTE=$(git remote -v | awk '{ print $2 }' | cut -d'@' -f2 | uniq | sed 's/https:\/\///' | sed 's/:/\//' | sed 's/github.com/docker.pkg.github.com/' | sed 's/\.git$//')
          FULLPATH=${REMOTE}/$(basename ${REMOTE})
          wget https://github.com/openshift/source-to-image/releases/download/v1.3.0/source-to-image-v1.3.0-eed2850f-linux-amd64.tar.gz -O /tmp/s2i.tar.gz
          tar -xzvf /tmp/s2i.tar.gz
          ./s2i build . singularo/s2i-shepherd-drupal ${FULLPATH}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${FULLPATH}
          tag_with_ref: true
