# This is a basic workflow to help you get started with Actions

name: Publish docker image

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ 9.0.x ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: redhat-cop/github-actions/s2i@master
        with:
          base: hub.docker.com/singularo/s2i-shepherd-drupal
          output_image: docker.pkg.github.com/singularo/shepherd-example-drupal/example-drupal
          image_push_registry: docker.pkg.github.com
          image_push_username: ${{ github.actor }}
          image_push_password: ${{ secrets.GITHUB_TOKEN }}
